
package gymbookingapp;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ben
 */
public class LogIn extends javax.swing.JFrame
{

    /**
     * Creates new form GUIJFrame
     */
    public LogIn()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton LogoLogin = new javax.swing.JButton();
        LogInHelp = new javax.swing.JLabel();
        LogInUsernameField = new javax.swing.JTextField();
        labelLogInUsername = new javax.swing.JLabel();
        labelLogInPassword = new javax.swing.JLabel();
        LogInPasswordField = new javax.swing.JPasswordField();
        LogInButton = new javax.swing.JButton();
        LogInForgottenPassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        MemberHelpPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        LogoLogin.setAlignmentY(0.0F);
        LogoLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogoLoginActionPerformed(evt);
            }
        });

        LogInHelp.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        LogInHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInHelp.setText("Help");
        LogInHelp.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                LogInHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                LogInHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                LogInHelpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376)
                .addComponent(LogInHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LogInHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        LogInUsernameField.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        LogInUsernameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogInUsernameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogInUsernameFieldActionPerformed(evt);
            }
        });

        labelLogInUsername.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        labelLogInUsername.setLabelFor(LogInUsernameField);
        labelLogInUsername.setText("Username");

        labelLogInPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        labelLogInPassword.setLabelFor(LogInPasswordField);
        labelLogInPassword.setText("Password");

        LogInPasswordField.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        LogInPasswordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogInPasswordField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                LogInPasswordFieldKeyPressed(evt);
            }
        });

        LogInButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        LogInButton.setText("Log In");
        LogInButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogInButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogInButtonActionPerformed(evt);
            }
        });

        LogInForgottenPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        LogInForgottenPassword.setText("Forgotten Your Password?");
        LogInForgottenPassword.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                LogInForgottenPasswordMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log In");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LogInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LogInForgottenPassword)
                        .addComponent(jLabel4))
                    .addComponent(labelLogInUsername)
                    .addComponent(labelLogInPassword)
                    .addComponent(LogInUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(labelLogInUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelLogInPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogInForgottenPassword)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel3.add(jPanel2, "card2");

        jLabel33.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Help and FAQs");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("All Help and FAQs for the gym including contact details will be displayed here.");
        jScrollPane5.setViewportView(jTextArea1);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("\"Icons used for Class Types made by Freepik & iconixar from www.flaticon.com\"\n");
        jScrollPane2.setViewportView(jTextArea3);

        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setText("Back to Log In");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MemberHelpPanelLayout = new javax.swing.GroupLayout(MemberHelpPanel);
        MemberHelpPanel.setLayout(MemberHelpPanelLayout);
        MemberHelpPanelLayout.setHorizontalGroup(
            MemberHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberHelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberHelpPanelLayout.createSequentialGroup()
                        .addGap(0, 369, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemberHelpPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(MemberHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MemberHelpPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MemberHelpPanelLayout.setVerticalGroup(
            MemberHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberHelpPanelLayout.createSequentialGroup()
                .addGroup(MemberHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberHelpPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberHelpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(MemberHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MemberHelpPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(MemberHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MemberHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LogoLoginActionPerformed
    {//GEN-HEADEREND:event_LogoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoLoginActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LogInButtonActionPerformed
    {//GEN-HEADEREND:event_LogInButtonActionPerformed
        String usr, nme;
        char[] pass;
        usr = LogInUsernameField.getText();
        pass = LogInPasswordField.getPassword();
        GymBookingApp gba = new GymBookingApp();
        try
        {
            if(gba.logInMember(usr, pass))
            {
                Member mem = gba.getMemberInfo(usr);
                nme = mem.name;
                AppMainUI HomePage = new AppMainUI();
                HomePage.setVisible(true);
                HomePage.pack();
                HomePage.setLocationRelativeTo(null);
                HomePage.WelcomeId.setText("Welcome Back " + nme + " Here's the Latest..");
                HomePage.UserName = mem.username;
                //get latest 5 news items
                String[][] news = gba.getNewsItems();
                //set latest news items with newest being shown first
                HomePage.News1.setText(news[0][0] + "\n" + "\n" + news[0][1]);
                HomePage.News2.setText(news[1][0] + "\n" + "\n" + news[1][1]);
                HomePage.News3.setText(news[2][0] + "\n" + "\n" + news[2][1]);
                HomePage.News4.setText(news[3][0] + "\n" + "\n" + news[3][1]);
                HomePage.News5.setText(news[4][0] + "\n" + "\n" + news[4][1]);
                //set friend request numbers
                ArrayList<String> requests = gba.getFriendRequests(usr);
                int reqNum = requests.size();
                if(reqNum > 0){
                HomePage.HomePageFriends.setText("Friends  " + reqNum);
                }
                //close current form
                this.dispose();
            }
            else if(gba.logInAdmin(usr, pass)){
                Trainer trnr = gba.getTrainerInfo(usr);
                Owner ownr = gba.getOwnerInfo(usr);
                if(trnr != null){
                    nme = trnr.name;
                    TrainerAppMainUI TrainerHomePage = new TrainerAppMainUI();
                    TrainerHomePage.setVisible(true);
                    TrainerHomePage.pack();
                    TrainerHomePage.setLocationRelativeTo(null);
                    TrainerHomePage.WelcomeId.setText("Welcome Back " + nme + " Here's the Latest..");
                    TrainerHomePage.Username = trnr.username;
                    //get latest 5 news items
                    String[][] news = gba.getNewsItems();
                    //set latest news items with newest being shown first
                    TrainerHomePage.News1.setText(news[0][0] + "\n" + "\n" + news[0][1]);
                    TrainerHomePage.News2.setText(news[1][0] + "\n" + "\n" + news[1][1]);
                    TrainerHomePage.News3.setText(news[2][0] + "\n" + "\n" + news[2][1]);
                    TrainerHomePage.News4.setText(news[3][0] + "\n" + "\n" + news[3][1]);
                    TrainerHomePage.News5.setText(news[4][0] + "\n" + "\n" + news[4][1]);
                    
                    //get latest trainer updates
                    String[][] updates = gba.getTrainerUpdates();
                    int x = updates.length - 1;
                    System.out.println(x);
                    TrainerHomePage.trainerNews.setText(updates[x][0] + "\n" + updates[x][1]
                                    + "\n" + "\n" + updates[x-1][0] + "\n" + updates[x-1][1]
                                    + "\n" + "\n" + updates[x-2][0] + "\n" + updates[x-2][1]
                                    + "\n" + "\n" + updates[x-3][0] + "\n" + updates[x-3][1]
                                    + "\n" + "\n" + updates[x-4][0] + "\n" + updates[x-4][1]);
                    this.dispose();
                } else{
                    nme = ownr.name;
                    OwnerAppMainUI OwnerHomePage = new OwnerAppMainUI();
                    OwnerHomePage.setVisible(true);
                    OwnerHomePage.pack();
                    OwnerHomePage.setLocationRelativeTo(null);
                    OwnerHomePage.WelcomeId.setText(nme);
                    OwnerHomePage.Username = ownr.username;
                    //get latest 5 news items
                    String[][] news = gba.getNewsItems();
                    //set latest news items with newest being shown first
                    OwnerHomePage.News1.setText(news[0][0] + "\n" + "\n" + news[0][1]);
                    OwnerHomePage.News2.setText(news[1][0] + "\n" + "\n" + news[1][1]);
                    OwnerHomePage.News3.setText(news[2][0] + "\n" + "\n" + news[2][1]);
                    OwnerHomePage.News4.setText(news[3][0] + "\n" + "\n" + news[3][1]);
                    OwnerHomePage.News5.setText(news[4][0] + "\n" + "\n" + news[4][1]);
                    this.dispose();
                }
            }
            else{
            JOptionPane.showMessageDialog(null, "Invalid Username or Password");
            }
            
        }
        catch (Exception ex)
        {
        }
    }//GEN-LAST:event_LogInButtonActionPerformed

    private void LogInForgottenPasswordMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LogInForgottenPasswordMouseClicked
    {//GEN-HEADEREND:event_LogInForgottenPasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInForgottenPasswordMouseClicked

    private void LogInUsernameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LogInUsernameFieldActionPerformed
    {//GEN-HEADEREND:event_LogInUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInUsernameFieldActionPerformed

    private void LogInPasswordFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_LogInPasswordFieldKeyPressed
    {//GEN-HEADEREND:event_LogInPasswordFieldKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        String usr, nme;
        char[] pass;
        usr = LogInUsernameField.getText();
        pass = LogInPasswordField.getPassword();
        GymBookingApp gba = new GymBookingApp();
        try
        {
            if(gba.logInMember(usr, pass))
            {
                Member mem = gba.getMemberInfo(usr);
                nme = mem.name;
                AppMainUI HomePage = new AppMainUI();
                HomePage.setVisible(true);
                HomePage.pack();
                HomePage.setLocationRelativeTo(null);
                HomePage.WelcomeId.setText("Welcome Back " + nme + " Here's the Latest..");
                HomePage.UserName = mem.username;
                
                //get latest 5 news items
                String[][] news = gba.getNewsItems();
                //set latest news items with newest being shown first
                HomePage.News1.setText(news[0][0] + "\n" + "\n" + news[0][1]);
                HomePage.News2.setText(news[1][0] + "\n" + "\n" + news[1][1]);
                HomePage.News3.setText(news[2][0] + "\n" + "\n" + news[2][1]);
                HomePage.News4.setText(news[3][0] + "\n" + "\n" + news[3][1]);
                HomePage.News5.setText(news[4][0] + "\n" + "\n" + news[4][1]);
                
                //set friend request numbers
                ArrayList<String> requests = gba.getFriendRequests(usr);
                int reqNum = requests.size();
                if(reqNum > 0){
                HomePage.HomePageFriends.setText("Friends  " + reqNum);
                }

                //close current form
                this.dispose();
            }
            else if(gba.logInAdmin(usr, pass)){
                Trainer trnr = gba.getTrainerInfo(usr);
                Owner ownr = gba.getOwnerInfo(usr);
                if(trnr != null){
                    nme = trnr.name;
                    TrainerAppMainUI TrainerHomePage = new TrainerAppMainUI();
                    TrainerHomePage.setVisible(true);
                    TrainerHomePage.pack();
                    TrainerHomePage.setLocationRelativeTo(null);
                    TrainerHomePage.WelcomeId.setText("Welcome Back " + nme + " Here's the Latest..");
                    TrainerHomePage.Username = trnr.username;
                    //get latest 5 news items
                    String[][] news = gba.getNewsItems();
                    //set latest news items with newest being shown first
                    TrainerHomePage.News1.setText(news[0][0] + "\n" + "\n" + news[0][1]);
                    TrainerHomePage.News2.setText(news[1][0] + "\n" + "\n" + news[1][1]);
                    TrainerHomePage.News3.setText(news[2][0] + "\n" + "\n" + news[2][1]);
                    TrainerHomePage.News4.setText(news[3][0] + "\n" + "\n" + news[3][1]);
                    TrainerHomePage.News5.setText(news[4][0] + "\n" + "\n" + news[4][1]);
                    
                    //get latest trainer updates
                    String[][] updates = gba.getTrainerUpdates();
                    TrainerHomePage.trainerNews.setText(updates[0][0] + "\n" + updates[0][1]
                                    + "\n" + "\n" + updates[1][0] + "\n" + updates[1][1]
                                    + "\n" + "\n" + updates[2][0] + "\n" + updates[2][1]
                                    + "\n" + "\n" + updates[3][0] + "\n" + updates[3][1]
                                    + "\n" + "\n" + updates[4][0] + "\n" + updates[4][1]);
                    this.dispose();
                } else{
                    nme = ownr.name;
                    OwnerAppMainUI OwnerHomePage = new OwnerAppMainUI();
                    OwnerHomePage.setVisible(true);
                    OwnerHomePage.pack();
                    OwnerHomePage.setLocationRelativeTo(null);
                    OwnerHomePage.WelcomeId.setText(nme);
                    OwnerHomePage.Username = ownr.username;
                    //get latest 5 news items
                    String[][] news = gba.getNewsItems();
                    //set latest news items with newest being shown first
                    OwnerHomePage.News1.setText(news[0][0] + "\n" + "\n" + news[0][1]);
                    OwnerHomePage.News2.setText(news[1][0] + "\n" + "\n" + news[1][1]);
                    OwnerHomePage.News3.setText(news[2][0] + "\n" + "\n" + news[2][1]);
                    OwnerHomePage.News4.setText(news[3][0] + "\n" + "\n" + news[3][1]);
                    OwnerHomePage.News5.setText(news[4][0] + "\n" + "\n" + news[4][1]);
                    this.dispose();
                }
            }
            else{
            JOptionPane.showMessageDialog(null, "Invalid Username or Password");
            }
            
        }
        catch (Exception ex)
        {
        }
    }
    }//GEN-LAST:event_LogInPasswordFieldKeyPressed

    private void LogInHelpMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LogInHelpMouseEntered
    {//GEN-HEADEREND:event_LogInHelpMouseEntered
        LogInHelp.setFont(new Font("SegoeUI Historic", Font.BOLD, 16));
    }//GEN-LAST:event_LogInHelpMouseEntered

    private void LogInHelpMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LogInHelpMouseExited
    {//GEN-HEADEREND:event_LogInHelpMouseExited
        LogInHelp.setFont(new Font("SegoeUI Historic", Font.PLAIN, 16));
    }//GEN-LAST:event_LogInHelpMouseExited

    private void LogInHelpMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LogInHelpMouseClicked
    {//GEN-HEADEREND:event_LogInHelpMouseClicked
        jPanel4.setVisible(true);
        jPanel2.setVisible(false);
        
    }//GEN-LAST:event_LogInHelpMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton1MouseClicked
    {//GEN-HEADEREND:event_jButton1MouseClicked
        jPanel4.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                LogIn LoginMember = new LogIn();
                LoginMember.setVisible(true);
                LoginMember.pack();
                LoginMember.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInButton;
    private javax.swing.JLabel LogInForgottenPassword;
    private javax.swing.JLabel LogInHelp;
    private javax.swing.JPasswordField LogInPasswordField;
    private javax.swing.JTextField LogInUsernameField;
    private javax.swing.JPanel MemberHelpPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel labelLogInPassword;
    private javax.swing.JLabel labelLogInUsername;
    // End of variables declaration//GEN-END:variables
}
